server:
  port: 1254
spring:
  redis:
    host: r-7xv5adiwdsscv7lygmpd.redis.rds.aliyuncs.com
    password: 564KUGBkjhMing
    database: 2
    port: 6379
    lettuce:
      pool:
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 10s